name: Mirror main branch to xhae000 personal repo

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from this repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to personal repo
        run: |
          git config --global user.email "xhae000@gmail.com"
          git config --global user.name "xhae000"

          git remote add personal https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/xhae000/raspy-mobile-mirror.git
          git push --force personal main:main
